# Generated by Django 2.2.1 on 2019-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sargams',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
