# Generated by Django 2.2.1 on 2019-10-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_sargam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sargam',
            old_name='notation',
            new_name='sargam',
        ),
    ]
