# Generated by Django 2.2.1 on 2020-03-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200314_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=200)),
            ],
        ),
    ]
