# Generated by Django 2.2.1 on 2020-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_sargams_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='sargams',
            name='youtube',
            field=models.TextField(blank=True, default='https://www.youtube.com/embed/f3YdJ6oBLVc'),
        ),
    ]
