# Generated by Django 2.2.1 on 2019-10-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0002_auto_20191022_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.CharField(max_length=40)),
                ('question', models.TextField(blank=True)),
                ('a', models.TextField(blank=True)),
                ('b', models.TextField(blank=True)),
                ('c', models.TextField(blank=True)),
                ('d', models.TextField(blank=True)),
                ('ans', models.TextField(blank=True)),
                ('qtype', models.CharField(max_length=40)),
            ],
        ),
    ]
