# Generated by Django 2.2.1 on 2019-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0004_test_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_1',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test_1',
            name='username',
            field=models.CharField(default='ccatcracker', max_length=100),
        ),
    ]
