# Generated by Django 2.2.1 on 2019-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0005_auto_20191023_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120)),
                ('a', models.TextField(blank=True)),
                ('b', models.TextField(blank=True)),
                ('c', models.TextField(blank=True)),
                ('d', models.TextField(blank=True)),
                ('ans', models.TextField(blank=True)),
                ('qtype', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='test_1',
            name='page',
        ),
        migrations.RemoveField(
            model_name='test_1',
            name='username',
        ),
    ]
