# Generated by Django 2.2.1 on 2019-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0007_auto_20191023_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='username',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
