# Generated by Django 2.2.1 on 2019-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0008_auto_20191023_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='qno',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
