# Generated by Django 2.2.1 on 2019-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0009_score_qno'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
