# Generated by Django 2.2.1 on 2019-11-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0010_score_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('a', models.TextField(blank=True)),
                ('b', models.TextField(blank=True)),
                ('c', models.TextField(blank=True)),
                ('d', models.TextField(blank=True)),
                ('ans', models.TextField(blank=True)),
                ('qtype', models.CharField(default='C++', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='test_1',
            name='qno',
            field=models.IntegerField(default=1),
        ),
    ]
