# Generated by Django 2.2.1 on 2019-11-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0011_auto_20191105_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_1',
            name='qno',
        ),
    ]
