# Generated by Django 2.2.1 on 2019-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_names', models.TextField(blank=True)),
                ('sargam', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('status', models.CharField(max_length=110)),
            ],
        ),
    ]
