# Generated by Django 2.2.1 on 2019-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chords',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
