# Generated by Django 2.2.1 on 2019-12-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0002_auto_20191213_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chords',
            name='url',
        ),
    ]
