# Generated by Django 2.2.1 on 2019-12-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0003_remove_chords_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chords',
            name='url',
            field=models.CharField(default='old', max_length=300),
        ),
    ]
