# Generated by Django 2.2.1 on 2020-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0006_chor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='chords',
            field=models.CharField(default='C Major,D Minor', max_length=300),
        ),
        migrations.AddField(
            model_name='chord',
            name='meta_disc',
            field=models.TextField(blank=True, default='new'),
        ),
        migrations.AddField(
            model_name='chord',
            name='meta_disc_os',
            field=models.TextField(blank=True, default='new'),
        ),
        migrations.AddField(
            model_name='chord',
            name='meta_key',
            field=models.TextField(blank=True, default='new'),
        ),
        migrations.AddField(
            model_name='chord',
            name='scale',
            field=models.CharField(default='C Major', max_length=300),
        ),
        migrations.AddField(
            model_name='chord',
            name='seo',
            field=models.TextField(blank=True, default='new'),
        ),
        migrations.AddField(
            model_name='chord',
            name='strum',
            field=models.CharField(default='D uud udu', max_length=300),
        ),
    ]
