# Generated by Django 2.2.1 on 2020-03-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0007_auto_20200315_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='chord',
            name='chords',
            field=models.CharField(default='C Major,D Minor', max_length=200),
        ),
        migrations.AlterField(
            model_name='chord',
            name='scale',
            field=models.CharField(default='C Major', max_length=200),
        ),
        migrations.AlterField(
            model_name='chord',
            name='strum',
            field=models.CharField(default='D uud udu', max_length=200),
        ),
        migrations.AlterField(
            model_name='chord',
            name='url',
            field=models.CharField(default='old', max_length=200),
        ),
    ]
