# Generated by Django 2.2.1 on 2019-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=111)),
                ('description', models.TextField(blank=True)),
                ('rank', models.CharField(max_length=111)),
                ('quality', models.CharField(max_length=111)),
                ('placement', models.CharField(max_length=111)),
                ('recommend', models.CharField(max_length=111)),
            ],
        ),
    ]
