# Generated by Django 2.2.1 on 2019-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=111)),
                ('rank', models.IntegerField()),
                ('placement', models.CharField(max_length=111)),
                ('recommend', models.CharField(max_length=111)),
            ],
        ),
    ]
