# Generated by Django 2.2.1 on 2019-08-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
