# Generated by Django 2.2.1 on 2019-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_cdac2019aug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('question', models.TextField(blank=True)),
                ('ans', models.TextField(blank=True)),
            ],
        ),
    ]
